1-map
zhurina50/purple-school-advanced pull request #1
Opened 2024-01-06 20:36 UTC by zhurina50

2024-01-08 19:49 UTC, Levitinn requested changes

2024-01-08 19:49 UTC, Levitinn commented on 1-map/app.js
> +    const res = [];
не нужно создавать переменную под массив, ты можешь сделать массив из Set
например так 
return Array.from(mySet);
https://doka.guide/js/array-from/

2024-01-10 02:34 UTC, zhurina50 commented on 1-map/app.js
> +    const res = [];
Я в сете храню только id. А пушу уже целый нужный объект. Если я буду добавлять в сет объекты - не будет уникализации. Если я сделаю массив из setId как есть сейчас - это будет массив из одних id - 1 2 3 4 , а не из объектов. Не понимаю, куда можно применить Array.from и как сделать лучше.

2024-01-11 14:23 UTC, Levitinn approved these changes

2024-01-11 14:23 UTC, Levitinn commented on 1-map/app.js
> +    const res = [];
> Я в сете храню только id. А пушу уже целый нужный объект. Если я буду добавлять в сет объекты - не будет уникализации. Если я сделаю массив из setId как есть сейчас - это будет массив из одних id - 1 2 3 4 , а не из объектов. Не понимаю, куда можно применить Array.from и как сделать лучше.

ты права, я не так понял твое решение. извиняюсь, за то что запутал))

2024-01-11 22:31 UTC, merged