11-geolocation
zhurina50/purple-school-advanced pull request #12
Opened 2024-02-01 01:26 UTC by zhurina50

2024-02-14 12:54 UTC, Levitinn requested changes

2024-02-14 12:54 UTC, Levitinn commented on 11-geolocation/app.js
> +   return new Promise((resolve, reject) => {
промис здесь не обязателен, скорее даже не нужен)

2024-02-14 12:54 UTC, Levitinn commented on 11-geolocation/app.js
> +   return new Promise((resolve, reject) => {
вот мой комментарий

2024-02-15 01:48 UTC, zhurina50 commented on 11-geolocation/app.js
> +   return new Promise((resolve, reject) => {
в задании сказано - обернуть в промис, создать свой промис. Мне тогда нужна подсказака, что от меня хотят.

2024-02-15 13:48 UTC, Levitinn commented on 11-geolocation/app.js
> +   return new Promise((resolve, reject) => {
прошу прощения. действительно, в задании просят промис. все ок

2024-02-15 13:48 UTC, Levitinn approved these changes

2024-02-16 03:41 UTC, merged